version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=mysql://malcolmclottey:Naakey057@@db:3306/malcolm_db
        depends_on:
            - redis
            - db

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: malcolm_db
            MYSQL_USER: malcolmclottey
            MYSQL_PASSWORD: Naakey057@
        ports:
            - "3306:3306"
