version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=postgresql://malcolmclottey:Naakey057@@db:5432/malcolm_db
        depends_on:
            - redis
            - db

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: malcolmclottey
            POSTGRES_PASSWORD: Naakey057@
            POSTGRES_DB: malcolm_db
        ports:
            - "5432:5432"
