version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=postgresql://malcolmclottey:Naakey057@@db:5432/malcolm_db
        depends_on:
            - redis
            - db
        restart: always  # Ensure the web service restarts on failure
        networks:
            - app-network

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        networks:
            - app-network

    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: malcolmclottey
            POSTGRES_PASSWORD: Naakey057@
            POSTGRES_DB: malcolm_db
        ports:
            - "5432:5432"
        networks:
            - app-network
        restart: always  # Ensure the database restarts on failure

# Define a network for the services to communicate with each other
networks:
    app-network:
